### ISSUE TITLE
No parent of path

### ISSUE THREAD

**Issue by AddictArts** [probablykasper/time-machine-inspector#5]
OS: 11.6.8

Checking out Tauri and came across this app. Thanks, helping me learn.

See picture. Maybe this should not be fatal and shut the whole thing down. The listed is just one of many backups.
<img width="260" alt="Screen Shot 2022-08-02 at 3 45 31 PM" src="https://user-images.githubusercontent.com/911906/182486288-d8def7c5-6cac-4784-8128-440029743538.png">

If there is no parent, then just skip it and don't list it?

**Comment by probablykasper** [comment]
I'm not facing this issue in my environment, so it might be a bit tough for me to figure out

I tried to fix it in https://github.com/probablykasper/time-machine-inspector/commit/50ccaffb606cf3aef80dd576c77acde7c49475bb, so looking at that should show where this error comes from. Issue #4 should be helpful to look at as well

**Comment by vtmocanu** [comment]
I get this too on 12.5 + Synology share for TM.

**Comment by probablykasper** [comment]
Could you let me know the output of `tmutil listbackups` and `tmutil machinedirectory`?

**Comment by vtmocanu** [comment]
```
❯ tmutil listbackups
2022-08-04-082038.backup
2022-08-05-075639.backup
2022-08-06-131835.backup
2022-08-06-141610.backup
2022-08-06-162459.backup
2022-08-06-173427.backup
2022-08-06-191115.backup
2022-08-07-091448.backup
2022-08-07-101915.backup
2022-08-07-111948.backup
2022-08-07-121847.backup
 13:03:46
❯ tmutil machinedirectory
/Volumes/Backups of farscape 1
```

thank you!

**Comment by probablykasper** [comment]
Thanks! Could you show the output of `ls $(tmutil machinedirectory)` as well?

**Comment by probablykasper** [comment]
I think it should be fixed in b4e70d699c68ef9e0a8b522d97252c663c42561d, would you be able to try it out?

If you have Tauri set up, you just need to run `npm install` and `npm run dev`

**Comment by vtmocanu** [comment]
Had to use quotes because the folder has spaces in name:
```
❯ ls $(tmutil machinedirectory)
ls: /Volumes/Backups: No such file or directory
ls: 1: No such file or directory
ls: farscape: No such file or directory
ls: of: No such file or directory
 11:25:16
❯ ls "$(tmutil machinedirectory)"
2022-08-08-110542.previous backup_manifest.plist
```

Don't have tauri, i'll wait for the release :)
Thank you!

**Comment by probablykasper** [comment]
Are those two the only ones in `/Volumes/Backups of farscape 1`? I would've expected all your backups to be in there. For me, that folder looks like this:
```
2022-04-17-230353/ 2022-07-10-195527/ 2022-07-16-192513/ 2022-07-24-193635/ 2022-07-30-212711/ 2022-08-07-203024/ 2022-08-08-052451/
2022-06-05-182708/ 2022-07-11-192425/ 2022-07-17-192621/ 2022-07-25-175429/ 2022-08-03-232121/ 2022-08-07-222325/ 2022-08-08-063806/
2022-06-12-200116/ 2022-07-12-182710/ 2022-07-18-200014/ 2022-07-26-201624/ 2022-08-04-212322/ 2022-08-07-232712/ 2022-08-08-074158/
2022-06-19-180023/ 2022-07-13-195939/ 2022-07-21-163712/ 2022-07-27-194329/ 2022-08-05-202418/ 2022-08-08-012120/ 2022-08-08-171100/
2022-06-26-171449/ 2022-07-14-180258/ 2022-07-22-193318/ 2022-07-28-192207/ 2022-08-06-191618/ 2022-08-08-022055/ 2022-08-08-174315/
2022-07-09-214953/ 2022-07-15-180723/ 2022-07-23-205627/ 2022-07-29-191729/ 2022-08-07-191214/ 2022-08-08-033018/ Latest@
```

**Comment by vtmocanu** [comment]
Yes, there are only 2 more hidden folders:
```
19:33:02:/Volumes/Backups of farscape 1 % ls -al
total 24
drwxr-xr-x@  6 root     wheel   192 Aug  8 19:07 .
drwxr-xr-x  18 root     wheel   576 Aug  8 19:32 ..
drwx------   4 vmocanu  staff   128 Aug  2 22:15 .Spotlight-V100
drwxr-xr-x   3 root     wheel    96 Aug  8 18:55 .com.apple.TimeMachine.IOCheck
drwxr-xr-x@  5 root     wheel   160 Aug  8 18:56 2022-08-08-190635.previous
-rw-r--r--@  1 root     wheel  8324 Aug  8 19:06 backup_manifest.plist
```

**Comment by AddictArts** [comment]
I ran the latest master and still get the error. Thanks for looking at it.
<img width="264" alt="Screen Shot 2022-08-08 at 5 10 15 PM" src="https://user-images.githubusercontent.com/911906/183535461-433e937f-c8a2-4ddb-8408-4b3764869465.png">

```
% ls $(tmutil machinedirectory)
ls: /Volumes/Time: No such file or directory
ls: Machine: No such file or directory
```

Note the default name Apple uses is "Time Machine". I'm very new to Rust, so I tried this, but it didn't work

```rust
let output_str = output_str.replace(" ", "\\ ");
```

So, I added some more code to item_entry
```
    println!("path {}", path.to_string_lossy());
    println!("root? {}", path.has_root());
```

and the machine_dir is not appended to the paths through the vec of strings to item_entry. The code runs in

```
      Some(machine_dir) => {
        *path = machine_dir.to_string() + "/" + &path;
        println!("some path {}", *path);
      }
```

Although for me the machine_dir had a "\n". This though never makes it to item_entry, so there is no parent.

**Comment by probablykasper** [comment]
@AddictArts That command actually needs to be `ls "$(tmutil machinedirectory)"`, my bad.

Let me try to explain a bit what commands TMI runs. If you can figure out how to do the same thing, TMI can just replicate that to get it working.

So let's say I wanna compare my two latest backups. I first run `tmutil listbackups`, which gives me a list of backups:
```sh
$ tmutil listbackups
// ...
/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-022017
/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-032130
```

Then, I want to compare those two to see what changed between them, so I run this command:
`
tmutil compare -X -s '/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-022017' '/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-032130'
`
And the result is a bunch of plist/xml stuff.

Now that I think about it, maybe it works to run it directly like this?
`tmutil compare -X -s 2022-08-07-111948.backup 2022-08-07-121847.backup`

**Comment by AddictArts** [comment]
Hi @probablykasper tmutil list backups does not include the complete path. It is just the folders. machine_dir has it.

This fixed it for me, sorry for the lame code, I'm new to rust.

```rust
  // let mut machine_dir = None;
  for path in paths.iter_mut() {
    if path.starts_with("/") {
      continue;
    }
    // match &machine_dir {
    //   None => {
        println!("tmutil machinedirectory");
        let output = Command::new("tmutil")
          .arg("machinedirectory")
          .output()
          .expect("Error calling command");
        check_cmd_success(&output.status, output.stderr.clone())?;
        println!("Success getting machinedirectory");
        let output_str = parse_output(output.stdout)?;
        println!("{}", output_str.replace(" ", "\\ "));
        let output_str = output_str.replace(" ", "\\ ");
        let output_str = output_str.replace("\n", "");
      //   machine_dir = Some(output_str);
      // }
      // Some(machine_dir) => {
      //   *path = machine_dir.to_string() + "/" + &path;
        *path = output_str + "/" + &path;
        println!("some path {}", *path);
      // }
    // }
  }
```

It's clear the Some() => was not being evaluated in the for loop and so item_entry got the basename which tmutil list backups returns, just the folder name, no absolute path like you show above.

**Comment by probablykasper** [comment]
Thanks, I'll have I look at it. I think that'll actually break it for me, because I assume this would add the machinedirectory to my `tmutil listbackups` which already are full paths

**Comment by vtmocanu** [comment]
I've tried the trial of BackupLoupe and that detected the snapshots ok.
Looks like it goes into the .timemachine folder:
```
❯ lsof -p 58739|grep -i volu
lsof: WARNING: can't stat() smbfs file system /Volumes/.timemachine/192.168.1.18/88B2C6D0-65A2-4CAE-B7DE-D02DA6D5EDAB/TimeMachine
      Output information may be incomplete.
      assuming "dev=360001c5" from mount table
BackupLou 58739 vmocanu  txt    REG               1,17     6967            22923927 /Applications/BackupLoupe.app/Contents/Resources/BackupVolumeFTemplate.pdf
```

**Comment by AddictArts** [comment]
@probablykasper I had been on a prior commit than your latest, sorry about that, so I think you may have had it close. I changed that section to this: Apologies, I know you might prefer a PR and I'll do that once it completely works if I keep hacking on it. You might arrive at a solution faster though.

This is fairly faithful to what you had; However, I can't wrap my head around the reason you didn't use the enum Option<> for the call to `tmutil listbackups`, but did for the call to `tmutil machinedirectory`? I'm very new to rust, but can't see how it is useful, `stored_machine_dir` is always None for example and creating the inline lambda to get the directory seems unneeded. Again I am just an outsider looking in, don't know what you ran into.

```rust
  println!("tmutil machinedirectory");
  let output = Command::new("tmutil")
    .arg("machinedirectory")
    .output()
    .expect("Error calling command");
  check_cmd_success(&output.status, output.stderr.clone())?;
  println!("Success getting machinedirectory");

  let output_str = parse_output(output.stdout)?.trim().to_owned();

  for path in paths.iter_mut() {
    if path.starts_with("/") {
      continue;
    } else {
      *path = output_str.to_owned() + "/" + &path;
    }
  }
```

That above works and seems to be very faithful to what you were going for, I really didn't add any code. Just small refactor, simplifying.

New error though now, which is why no PR.


<img width="268" alt="Screen Shot 2022-08-09 at 9 07 34 AM" src="https://user-images.githubusercontent.com/911906/183703011-d205b7e1-da2c-40dd-8cb8-afcf2965afad.png">

**Comment by AddictArts** [comment]
@probablykasper here is the error now

```
tmutil compare -X -s '/Volumes/Time Machine/2021-08-26-094923.backup' '/Volumes/Time Machine/2021-09-08-091030.backup'
⏱  0.813ms running tmutil
Error: tmutil error 64:
Can't compare a source volume descendant to a source volume descendant.
```

Are you using an old version of Mac OS? Time Machine has changed and the paths in the terminal with full disk access are not the same. For example if I `ls /Volumes/Time Machine` I just get a `.previous` folder name.

**Comment by probablykasper** [comment]
Does it work if you run `tmutil compare -X -s '2021-08-26-094923.backup' '2021-09-08-091030.backup'`?

The reason for using `Option<>` is that `tmutil machinedirectory` doesn't need to run in all cases. So if `tmutil listbackups` gives the full paths (like it does for me), there's no need to run that command

**Comment by AddictArts** [comment]
> Does it work if you run `tmutil compare -X -s '2021-08-26-094923.backup' '2021-09-08-091030.backup'`?
> 
> The reason for using `Option<>` is that `tmutil machinedirectory` doesn't need to run in all cases. So if `tmutil listbackups` gives the full paths (like it does for me), there's no need to run that command

You check for that though in the for loop, `if path.starts_with("/") { ... continue`

That tmutil compare results in `Must specify at least one item inside a backup.` Thanks

**Comment by probablykasper** [comment]
> You check for that though in the for loop, `if path.starts_with("/") { ... continue`

Without the `Option`, `tmutil machinedirectory` would have to run on each iteration.

lmk if you're able to figure out how to run `tmutil compare`, that's what would be needed to fix it

**Comment by gridsystem** [comment]
I'm also having this `no parent of path` issue. I may have had a failed backup on the date in the error message. After the error I hit "Back up now" in TM and it succeeded. I wish I'd taken more notice of the message on the day it failed as it might have helped you. Let me know if there's anything I could do to contribute.

**Comment by probablykasper** [comment]
@gridsystem If you're able to successfully run `tmutil compare` and share the commands you had to run, that would be helpful

This is how it works for me:

```sh
$ tmutil listbackups
/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-022017
/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-032130

tmutil compare -X -s '/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-022017' '/Volumes/Time Machine Backups/Backups.backupdb/kasper-imac-2019/2022-08-09-032130'
```

**Comment by gridsystem** [comment]
I might be being dense but what should I compare? Any two snapshots or two in particular?

**Comment by probablykasper** [comment]
The last two (though it doesn't really matter, I just need to see the command working and how you got there)

**Comment by probablykasper** [comment]
Should be fixed in [v1.2.0](https://github.com/probablykasper/time-machine-inspector/releases/tag/v1.2.0)
